#Import Library

In [0]:
import pandas as pd
import numpy as np

#Series คล้ายๆกับ Vector (Array 1 มิติ)
1Key 1 Value

In [0]:
score = [90, 99, 85]
age = [29, 30, 31]

dict1 = {'MariKoh': [score[0], age[0]],
         'John': [score[1], age[1]],
         'Smith': [score[2], age[2]]}

In [8]:
dict1

{'John': [99, 30], 'MariKoh': [90, 29], 'Smith': [85, 31]}

In [9]:
pd.Series(dict1) #แปลงจาก Dictionary เป็น Series Key => Label

MariKoh    [90, 29]
John       [99, 30]
Smith      [85, 31]
dtype: object

In [0]:
Name = ['MariKoh', 'John', 'Smith']

In [11]:
series = pd.Series(score, Name, dtype=int)
print(series)

MariKoh    90
John       99
Smith      85
dtype: int64


In [0]:
score2 = np.array(score)

name2 = np.array(Name)

print(type(score2))
print(type(name2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [0]:
series2 = pd.Series(score2, name2)

print(series2)
print(series2.index)
print(type(series2.values))

MariKoh    90
John       99
Smith      85
dtype: int64
Index(['MariKoh', 'John', 'Smith'], dtype='object')
<class 'numpy.ndarray'>


In [0]:
series3 = pd.Series(['MariKoh', 'BieBird', 'Rathy', 'NutTwin'])
print(series3)
print(series3[0])
print(series3[0:2])

0    MariKoh
1    BieBird
2      Rathy
3    NutTwin
dtype: object
MariKoh
0    MariKoh
1    BieBird
dtype: object


In [0]:
print(series3[[0, 3]])

0    MariKoh
3    NutTwin
dtype: object


In [0]:
score = [90, 75, 72, 80, 94, 86]
name = ['MariKoh', 'BieBird', 'Rathy', 'NutTwin', 'BigBoss', 'Nicky']

series = pd.Series(score, name)
print(series)

even_number = np.arange(0, len(score), 2)
print(series[even_number])

even_number2 = np.arange(6)
print(series[even_number2 % 2 != 0])

MariKoh    90
BieBird    75
Rathy      72
NutTwin    80
BigBoss    94
Nicky      86
dtype: int64
BieBird    75
NutTwin    80
Nicky      86
dtype: int64
BieBird    75
NutTwin    80
Nicky      86
dtype: int64


In [0]:
series.argmax()

4

In [0]:
#การแก้ไขสมาชิกภายใน ทำคล้ายๆกับ Dictionary

series['Somchai'] = 15

print(series)

MariKoh    90
BieBird    75
Rathy      72
NutTwin    80
BigBoss    94
Nicky      86
Somchai    15
dtype: int64


In [0]:
#del

del series['Somchai']

print(series)

MariKoh    90
BieBird    75
Rathy      72
NutTwin    80
BigBoss    94
Nicky      86
dtype: int64


In [0]:
# score = [90, 75, 72, 80, 94, 86]
# age = [29, 28, 27, 26, 25, 24]
# name = ['MariKoh', 'BieBird', 'Rathy', 'NutTwin', 'BigBoss', 'Nicky']

# series = pd.Series(data=[score, age], index=name)
# print(series)

ValueError: ignored

In [0]:
#Mid Term & Final
scoremid = [90, 75, 72, 80, 94, 86]
scorefin = [60, 70, 80, 90, 80, 70]
age = [29, 28, 27, 26, 25, 24]
name = ['MariKoh', 'BieBird', 'Rathy', 'NutTwin', 'BigBoss', 'Nicky']
name2 = ['MariKoh', 'BieBird', 'Rathy', 'NutTwin', 'BigBoss', 'Nicky']

series1 = pd.Series(scoremid, name)
series2 = pd.Series(scorefin, name)

print(series1 + series2)

MariKoh    150
BieBird    145
Rathy      152
NutTwin    170
BigBoss    174
Nicky      156
dtype: int64


#Data Frame คล้ายๆ Array 2 มิติ (Matrix)

In [0]:
values = np.random.randint(1, 21, (3, 3))
print(values)

[[14 11 15]
 [ 5  4 12]
 [11 19 18]]


In [0]:
rows = ['A', 'B', 'C']
cols = ['C1', 'C2', 'C3']

In [0]:
df = pd.DataFrame(values, rows, cols)
df

C1  C2  C3
A  14  11  15
B   5   4  12
C  11  19  18

In [0]:
#Slice หลาย Column
df[['C1', 'C3', 'C2']][0:1]

C1  C3  C2
A  14  15  11

In [0]:
df['C4'] = [1, 2, 3]
df

C1  C2  C3  C4
A  14  11  15   1
B   5   4  12   2
C  11  19  18   3

In [0]:
df.drop('C4', axis=1) #แค่แสดงผล
print(df)

   C1  C2  C3  C4
A  14  11  15   1
B   5   4  12   2
C  11  19  18   3


In [0]:
df.drop(labels='C4', axis=1, inplace=True) #ถ้า Inplace คือการไปทับค่าเดิม
print(df)

   C1  C2  C3
A  14  11  15
B   5   4  12
C  11  19  18


In [0]:
#เข้าถึงโดยใช้ iloc (เข้าโดย Rows) ใส่เลข Index

df.iloc(1) #จะ Print(ต้องเอามาใส่ List ก่อนเพื่อแสดงผล)
print([df.iloc[1]])

[C1     5
C2     4
C3    12
Name: B, dtype: int64]


In [0]:
df.loc['A'] #เข้าถึงโดยใส่ชื่อ

C1    14
C2    11
C3    15
Name: A, dtype: int64

In [0]:
df

C1  C2  C3
A  14  11  15
B   5   4  12
C  11  19  18

In [0]:
print(df.loc['B', 'C3'])

12


In [0]:
print(df.loc[['A', 'B'], ['C1', 'C3']])

   C1  C3
A  14  15
B   5  12


In [0]:
print(df.loc[['A', 'B'], 'C1'])

A    14
B     5
Name: C1, dtype: int64


In [0]:
#if else
values = np.random.randint(1, 100, (5, 5))
rows = ['A', 'B', 'C', 'D', 'E']
cols = ['C1', 'C2', 'C3', 'C4', 'C5']

df = pd.DataFrame(data=values, index=rows, columns=cols)
df

C1  C2  C3  C4  C5
A  74  71   1  59  67
B  87  46   4  43  87
C  23  98  98  45  11
D  34  73  59  51  85
E  86  10  57  27  91

In [0]:
df > 50

C1     C2     C3     C4     C5
A   True   True  False   True   True
B   True  False  False  False   True
C  False   True   True  False  False
D  False   True   True   True   True
E   True  False   True  False   True

In [0]:
df[df>50]

C1    C2    C3    C4    C5
A  74.0  71.0   NaN  59.0  67.0
B  87.0   NaN   NaN   NaN  87.0
C   NaN  98.0  98.0   NaN   NaN
D   NaN  73.0  59.0  51.0  85.0
E  86.0   NaN  57.0   NaN  91.0

In [0]:
df[df['C3'] > 30] #เอาทุก Rows ที่ ค่าใน C3 มากกว่า 30 ในที่นื้คือเอา A B ออกเพราะค่าใน C3 < 30

C1  C2  C3  C4  C5
C  23  98  98  45  11
D  34  73  59  51  85
E  86  10  57  27  91

In [0]:
df[df['C3'] > 30]['C5']

C    11
D    85
E    91
Name: C5, dtype: int64

In [0]:
df[df['C3'] > 30][['C5', 'C4']]

C5  C4
C  11  45
D  85  51
E  91  27

In [0]:
df

C1  C2  C3  C4  C5
A  74  71   1  59  67
B  87  46   4  43  87
C  23  98  98  45  11
D  34  73  59  51  85
E  86  10  57  27  91

In [0]:
#มากกว่า 1 เงื่อนไข
df[['C1', 'C3']][1:3]

C1  C3
B  87   4
C  23  98

In [0]:
df['C3'] < 70

A     True
B     True
C    False
D     True
E     True
Name: C3, dtype: bool

In [0]:
df[df['C3'] < 70]

C1  C2  C3  C4  C5
A  74  71   1  59  67
B  87  46   4  43  87
D  34  73  59  51  85
E  86  10  57  27  91

In [0]:
df[df['C4'] > 50]

C1  C2  C3  C4  C5
A  74  71   1  59  67
D  34  73  59  51  85

In [0]:
df[(df['C4'] > 50) & (df['C3'] < 70)] #& คือหาตัวซ้ำ

C1  C2  C3  C4  C5
A  74  71   1  59  67
D  34  73  59  51  85

In [0]:
#Multi Index
level1 = ['รถญี่ปุ่น', 'รถญี่ปุ่น', 'รถญี่ปุ่น', 'รถยุโรป', 'รถยุโรป', 'รถยุโรป']
level2 = ['ฮอนด้า', 'โตโยต้า', 'นิสสัน', 'เบ๊นซ์', 'บีเอ็ม', 'พอร์เช่']
cols = ['ยอดขายปี 2018 (Mb)', 'ยอดขายปี 2019 (Mb)']

print(level1)
print(level2)
print(cols)

index = list(zip(level1, level2))
print(index)

revenue = np.random.randint(5, 50, (6, 2))
print(revenue)

['รถญี่ปุ่น', 'รถญี่ปุ่น', 'รถญี่ปุ่น', 'รถยุโรป', 'รถยุโรป', 'รถยุโรป']
['ฮอนด้า', 'โตโยต้า', 'นิสสัน', 'เบ๊นซ์', 'บีเอ็ม', 'พอร์เช่']
['ยอดขายปี 2018 (Mb)', 'ยอดขายปี 2019 (Mb)']
[('รถญี่ปุ่น', 'ฮอนด้า'), ('รถญี่ปุ่น', 'โตโยต้า'), ('รถญี่ปุ่น', 'นิสสัน'), ('รถยุโรป', 'เบ๊นซ์'), ('รถยุโรป', 'บีเอ็ม'), ('รถยุโรป', 'พอร์เช่')]
[[36 18]
 [42  8]
 [46 16]
 [25 11]
 [32 44]
 [32  9]]


In [0]:
index

[('รถญี่ปุ่น', 'ฮอนด้า'),
 ('รถญี่ปุ่น', 'โตโยต้า'),
 ('รถญี่ปุ่น', 'นิสสัน'),
 ('รถยุโรป', 'เบ๊นซ์'),
 ('รถยุโรป', 'บีเอ็ม'),
 ('รถยุโรป', 'พอร์เช่')]

In [0]:
multi_index = pd.MultiIndex.from_tuples(index)

df = pd.DataFrame(data=revenue, index=multi_index, columns=cols)
print(df)

                   ยอดขายปี 2018 (Mb)  ยอดขายปี 2019 (Mb)
รถญี่ปุ่น ฮอนด้า                   36                  18
          โตโยต้า                  42                   8
          นิสสัน                   46                  16
รถยุโรป   เบ๊นซ์                   25                  11
          บีเอ็ม                   32                  44
          พอร์เช่                  32                   9


#Series

In [6]:
Score = [90, 80, 69, 79, 40]
Name = ['MariKoh', 'John ชาวไร่', 'John Wick', 'John Snow', 'Johnny']

S = pd.Series(data=Score, index=Name, dtype=int, name='Students Name')
print(S)

MariKoh        90
John ชาวไร่    80
John Wick      69
John Snow      79
Johnny         40
Name: Students Name, dtype: int64


In [10]:
Score2 = np.array(Score)
Name2 = np.array(Name)

S2 = pd.Series(index = Name2,
               data = Score2,
               dtype = int,
               name = 'Students Name')

print(type(Score2))
print(type(Name2))
print(S2)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
MariKoh        90
John ชาวไร่    80
John Wick      69
John Snow      79
Johnny         40
Name: Students Name, dtype: int64


In [11]:
print(f'Series Value = {S2.values}')
print(f'Series Index = {S2.index}')

Series Value = [90 80 69 79 40]
Series Index = Index(['MariKoh', 'John ชาวไร่', 'John Wick', 'John Snow', 'Johnny'], dtype='object')


In [15]:
print(S2[:2])

MariKoh        90
John ชาวไร่    80
Name: Students Name, dtype: int64


In [17]:
print(S2[[0, 2, 4]]) #Slice ค่าเดียว

MariKoh      90
John Wick    69
Johnny       40
Name: Students Name, dtype: int64


In [18]:
print(S2[::2])

MariKoh      90
John Wick    69
Johnny       40
Name: Students Name, dtype: int64


In [22]:
Score = [90, 80, 69, 79, 40, 99]
Name = ['MariKoh', 'John ชาวไร่', 'John Wick', 'John Snow', 'Johnny', 'John Bollinger']

num = np.arange(6) #สร้าง Array เก็บค่า 0-5 ขึ้นมา ทำเป็น Boolean แล้วเราจะเอาเลขคู่

S3 = pd.Series(data=Score,
               index=Name)

S3[num % 2 == 0] #เอาเลขคู่

MariKoh      90
John Wick    69
Johnny       40
dtype: int64

In [23]:
S3[num % 2 == 1] #เอาเลขคี่

John ชาวไร่       80
John Snow         79
John Bollinger    99
dtype: int64

In [24]:
print(num % 2 == 0)

[ True False  True False  True False]


In [25]:
S3.sum()

457

In [28]:
round(S3.mean(), 2)

76.17

In [29]:
S3.argmax()

5

In [31]:
S3['MariKoh'] = 95
S3

MariKoh           95
John ชาวไร่       80
John Wick         69
John Snow         79
Johnny            40
John Bollinger    99
dtype: int64

In [32]:
S3['John ABAC'] = 30
S3

MariKoh           95
John ชาวไร่       80
John Wick         69
John Snow         79
Johnny            40
John Bollinger    99
John ABAC         30
dtype: int64

In [33]:
del S3['John ชาวไร่']
S3

MariKoh           95
John Wick         69
John Snow         79
Johnny            40
John Bollinger    99
John ABAC         30
dtype: int64

In [34]:
S3['John The Farmer'] = 97
S3

MariKoh            95
John Wick          69
John Snow          79
Johnny             40
John Bollinger     99
John ABAC          30
John The Farmer    97
dtype: int64

In [35]:
Mid_Score = [90, 80, 69, 79, 40, 99]
Fin_Score = [90, 80, 77, 34, 80, 70]
Name = ['MariKoh', 'John The Farmer', 'John Wick', 'John Snow', 'Johnny', 'John Bollinger']

S4 = pd.Series(data=Mid_Score,
               index=Name,
               dtype=int,
               name='Midterm Score')

S5 = pd.Series(data=Fin_Score,
               index=Name,
               dtype=int,
               name='Final Score')

print(S4)
print(S5)
print(S4+S5)

MariKoh            90
John The Farmer    80
John Wick          69
John Snow          79
Johnny             40
John Bollinger     99
Name: Midterm Score, dtype: int64
MariKoh            90
John The Farmer    80
John Wick          77
John Snow          34
Johnny             80
John Bollinger     70
Name: Final Score, dtype: int64
MariKoh            180
John The Farmer    160
John Wick          146
John Snow          113
Johnny             120
John Bollinger     169
dtype: int64


#Data Frame

In [37]:
val = np.random.randint(low=0,
                        high=20,
                        size=(3, 3))

rows = ['A', 'B', 'C']
cols = ['X', 'Y', 'Z']

Data = pd.DataFrame(data=val,
                    index=rows,
                    columns=cols)

print(Data)

    X   Y   Z
A   7  19  18
B  18  16   4
C  19   9  18


In [38]:
Data

X   Y   Z
A   7  19  18
B  18  16   4
C  19   9  18

In [40]:
Data.shape

(3, 3)

In [56]:
Data[['X', 'Y']]['A':'B'] #Slide ด้วยชื่อ Rows ตัวหลัง : จะ Inclusive แต่ถ้า Slice ด้วยเลข [0:3] ตัวหลัง : จะเป็น Exclusive

X   Y
A   7  19
B  18  16

In [47]:
type(Data[['X', 'Y']])

pandas.core.frame.DataFrame

In [48]:
type(Data['X'])

pandas.core.series.Series

In [57]:
Data['P'] = [1, 2, 3]
Data

X   Y   Z  P
A   7  19  18  1
B  18  16   4  2
C  19   9  18  3

In [59]:
Data.insert(loc=0,
            column='Q',
            value=[1, 2, 3])

ValueError: ignored

In [61]:
Data['Q'] = [7, 8, 9]
del Data[0]

Data

Q   X   Y   Z  P
A  7   7  19  18  1
B  8  18  16   4  2
C  9  19   9  18  3

In [66]:
Data.drop(labels='C',
          axis=0)

Q   X   Y   Z  P
A  7   7  19  18  1
B  8  18  16   4  2

In [67]:
Data

Q   X   Y   Z  P
A  7   7  19  18  1
B  8  18  16   4  2
C  9  19   9  18  3

In [69]:
Data.loc['D'] = [1, 3, 5, 7, 9]
Data

Q   X   Y   Z  P
A   7   7  19  18  1
B   8  18  16   4  2
C   9  19   9  18  3
-1  1   3   5   7  9
D   1   3   5   7  9

In [72]:
Data.drop(labels=-1,
          axis=0,
          inplace=True)

Data

Q   X   Y   Z  P
A  7   7  19  18  1
B  8  18  16   4  2
C  9  19   9  18  3
D  1   3   5   7  9

In [73]:
Data.shape

(4, 5)

In [74]:
Data.loc['F'] = [9, 8, 7, 6, 5]
Data

Q   X   Y   Z  P
A  7   7  19  18  1
B  8  18  16   4  2
C  9  19   9  18  3
D  1   3   5   7  9
F  9   8   7   6  5

In [78]:
Data.loc[['A', 'B']][['X', 'Y', 'Z']]

X   Y   Z
A   7  19  18
B  18  16   4

In [79]:
Data

Q   X   Y   Z  P
A  7   7  19  18  1
B  8  18  16   4  2
C  9  19   9  18  3
D  1   3   5   7  9
F  9   8   7   6  5

In [80]:
Data[Data > 5]

Q     X     Y     Z    P
A  7.0   7.0  19.0  18.0  NaN
B  8.0  18.0  16.0   NaN  NaN
C  9.0  19.0   9.0  18.0  NaN
D  NaN   NaN   NaN   7.0  9.0
F  9.0   8.0   7.0   6.0  NaN

In [87]:
Data[Data['X'] > 5]

Q   X   Y   Z  P
B  8  18  16   4  2
C  9  19   9  18  3

In [88]:
Data[Data['X'] > 5]['P']

A    1
B    2
C    3
F    5
Name: P, dtype: int64

In [89]:
Data[Data['X'] > 5][['P', 'Z']]

P   Z
A  1  18
B  2   4
C  3  18
F  5   6

In [94]:
Data[Data['X'] > 5]

Q   X   Y   Z  P
A  7   7  19  18  1
B  8  18  16   4  2
C  9  19   9  18  3
F  9   8   7   6  5

In [96]:
Data[Data['P'] > 2]

Q   X  Y   Z  P
C  9  19  9  18  3
D  1   3  5   7  9
F  9   8  7   6  5

In [93]:
Data[(Data['X'] > 5) & (Data['P'] > 2)]

Q   X  Y   Z  P
C  9  19  9  18  3
F  9   8  7   6  5

In [101]:
L1 = ['รถญี่ปุ่น', 'รถญี่ปุ่น', 'รถญี่ปุ่น', 'รถยุโรป', 'รถยุโรป', 'รถยุโรป']
L2 = ['ฮอนด้า', 'โตโยต้า', 'นิสสัน', 'Benz', 'BMW', 'Porche']
col = ['ยอดขายปี 2019 (Billion Bath)', 'ยอดขายปี 2020 (Billion Bath)']
index = list(zip(L1, L2))

Multi_Index = pd.MultiIndex.from_tuples(index)

income = np.random.randint(low=5,
                           high=50,
                           size=(6, 2))

Sale = pd.DataFrame(data=income,
                    index=Multi_Index,
                    columns=col)
Sale

ยอดขายปี 2019 (Billion Bath)  ยอดขายปี 2020 (Billion Bath)
รถญี่ปุ่น ฮอนด้า                              8                            25
          โตโยต้า                            34                            36
          นิสสัน                              9                            35
รถยุโรป   Benz                                9                            18
          BMW                                21                            29
          Porche                              6                             5